spring:
  datasource:
    url: jdbc:postgresql://localhost:4814/queueApp?useSSL=false
    username: postgres
    password: 4814

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: create-drop
